spring:
  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/movies?useSSL=false
    username: root
    password: Anju@2510

  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp

<<<<<<< HEAD
s3:
    endpointUrl: http://127.0.0.1:9000
    accessKey: DS0BL6XYYODH671EAEMR
    secretKey: FWqltcOhC8G9WNP/c6pUcyru4VyBPOfk/V5lWMlK
    bucketName: moviefun

logging.level:
    root: INFO
    org.superbiz.moviefun: DEBUG
=======
logging.level:
  root: WARN
  org.superbiz.moviefun: DEBUG

s3:
  endpointUrl: <aws endpoint>
  accessKey: <access key id>
  secretKey: <secret access key>
  bucketName: <name of the bucket>
>>>>>>> e5c4579... Import Albums from BlobStore at regular interval.
